from pathlib import Path

import typer

ENV_PYRROWHEAD_DIRECTORY = 'PYRROWHEAD_INSTALL_DIRECTORY'
ENV_PYRROWHEAD_ACTIVE_CLOUD = 'PYRROWHEAD_ACTIVE_CLOUD'
APP_NAME = 'pyrrowhead'
LOCAL_CLOUDS_SUBDIR = 'local-clouds'
CLOUD_CONFIG_FILE_NAME = 'cloud_config.yaml'
CONFIG_FILE = 'config.cfg'