name: CI

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest"]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install docker (macos only)
      uses: docker-practice/actions-setup-docker@master
      if: matrix.os == 'macos-latest'
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Determine tox environment name
      run: |
    - name: Test with tox
      env:
        TOX_ENV: py${${${{matrix.python-version}}//./}}
      run: |
        PYVER=${{matrix.python-version}}
        TOX_ENV_VERSION=${PYVER//./}
        TOX_ENV_NAME=py${TOX_ENV_VERSION}
        echo $TOX_ENV_NAME
        tox -e $TOX_ENV_NAME
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Check code conforms to Black
        run: tox -e black
      - name: Check typing
        run: tox -e mypy
        env:
          PLATFORM: ${{ matrix.platform }}

