on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          python -m pip install --upgrade setuptools
          python -m pip install build
          python -m build
          python -m pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create cloud
        run: |
          pyrrowhead cloud create test-cloud.test-org
          echo Pyrrowhead dir check...
          test -d ~/.pyrrowhead
          echo test-cloud config file created check...
          test -f ~/.pyrrowhead/local-clouds/test-org/test-cloud/cloud_config.yaml
      - name: Install cloud
        run: |
          pyrrowhead cloud install test-cloud.test-org
          echo Certificates created check...
          test -f ~/.pyrrowhead/local-clouds/test-org/test-cloud/certs/crypto/service_registry.crt

