name: Docs

on:
  push:
    paths:
      - 'docs/'
  pull_request:
    paths:
      - 'docs/'

jobs:
    docs:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.10"]
      steps:
        - uses: actions/checkout@v1
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install tox tox-gh-actions
        - name: Build docs
          run: tox -e docs
          env:
            PLATFORM: ${{ matrix.platform }}
